name: flutter_notification
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  device_info: ^2.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_timezone: ^1.0.8
  http: ^1.2.0
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  timezone: ^0.9.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/coworker.png
  plugin:
    platforms:
      android:
        package: com.dexterous.flutterlocalnotifications
        pluginClass: FlutterLocalNotificationsPlugin
      ios:
        pluginClass: FlutterLocalNotificationsPlugin
      macos:
        pluginClass: FlutterLocalNotificationsPlugin
      linux:
        default_package: flutter_local_notifications_linux

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  adaptive_icon_backgrounnd: "#ffffff"
  adaptive_icon_foregroud: "assets/images/background.png"
